version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
